repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
#      - id: tflint
#        args:
#          - "--module"
#          - "--config=.tflint.hcl"
      - id: terraform-validate
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_tfsec
        args:
          - --args=-e aws-cloudfront-enable-logging,aws-cloudfront-enable-waf,aws-s3-enable-bucket-logging
      - id: terraform_docs
